# Default settings (for English)
title: "Federico Dattila - Il cacciatore di anidride carbonica"
email: "federico.dattila@polito.it"
description: "Benvenuti sul mio sito personale, con informazioni su di me, sulla mia research, e sulle mia attività comunicative."
baseurl: ""  # The subpath of your site, e.g., /blog
url: "https://fededat.github.io"  # Your GitHub Pages URL
lang: "it"  # Default language is English

# Navigation configuration
nav:
  en:
    - Home: /en/
    - About Federico: /en/about-federico/
    - Book an activity: /en/communication/
    - Upcoming Events: /en/events/
    - Research: /en/research/
    - Courses: /en/courses/
    - Contacts: /en/contacts/

  it:
    - Home: /
    - Chi sono: /it/federico/
    - Prenota un'attività: /it/comunicazione/
    - Eventi: /it/eventi/
    - Ricerca: /it/ricerca/
    - Corsi: /it/corsi/
    - Contatti: /it/contatti/

# Italian language configuration
defaults:
  - scope:
      path: "it"
      type: "pages"
    values:
      nav: "it"
      lang: "it"
  - scope:
      path: "en"
      type: "pages"
    values:
      nav: "en"
      lang: "en"


# Adding the Italian version of the site
languages:
  - lang: "en"
    url: "/en/"
    title: "Federico Dattila - The carbon dioxide hunter"
  - lang: "it"
    url: "/it/"
    title: "Federico Dattila - Il cacciatore di anidride carbonica"

# Exclude files from processing
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-multilingual  # Add this plugin

# Theme configuration (optional, if using a specific theme)
theme: minima

# Footer information
footer:
  hosting: "Hosted on GitHub Pages"
  theme_credit: "Using Minima theme"

# SEO settings
jekyll-seo-tag:
  lang: "it"
  author: "Federico Dattila"

# Language selector
language_selector: true

