# Default settings (for English)
title: "Federico Dattila - Il cacciatore di anidride carbonica"
email: "federico.dattila@polito.it"
description: "Benvenuti sul mio sito personale, con informazioni su di me, sulle mie ricerche, e sulle mie attività di comunicazione."
baseurl: ""  # The subpath of your site, e.g., /blog
url: "https://fededat.github.io"  # Your GitHub Pages URL

# Navigation configuration
nav:
  - Home: /
  - Chi sono: /it/federico/
  - Prenota un'attività: /it/comunicazione/
  - Eventi: /it/eventi/
  - Ricerca: /it/ricerca/
  - Corsi: /it/corsi/
  - Contatti: /it/contatti/

# Exclude files from processing
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Theme configuration (optional, if using a specific theme)
theme: minima

# Footer information
footer:
  hosting: "Hosted on GitHub Pages"
  theme_credit: "Using Minima theme"

# SEO settings
jekyll-seo-tag:
  author: "Federico Dattila"
