# Default settings (for English)
title: "Federico Dattila - Il cacciatore di anidride carbonica"
email: "federico.dattila@polito.it"
description: "Benvenuti sul mio sito personale, con informazioni su di me, sulle mie ricerche, e sulle mie attività di comunicazione."
baseurl: ""  # The subpath of your site, e.g., /blog
url: "https://fededat.github.io"  # Your GitHub Pages URL

# Navigation configuration
nav:
  - Home: /
  - Chi sono: /federico/
  - Prenota un'attività: /comunicazione/
  - Eventi: /eventi/
  - Ricerca: /ricerca/
  - Corsi: /corsi/
  - Contatti: /contatti/


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - {title: "Home", path: "/"}
  - {title: "Chi sono", path: "/federico/"}
  - {title: "Prenota un'attività", path: "/comunicazione/"}
  - {title: "Eventi", path: "/eventi/"}
  - {title: "Ricerca", path: "/ricerca/"}
  - {title: "Corsi", path: "/corsi/"}
  - {title: "Contatti", path: "/contatti/"}

# Exclude files from processing
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Theme configuration (optional, if using a specific theme)
theme: minima

# Footer information
footer:
  hosting: "Hosted on GitHub Pages"
  theme_credit: "Using Minima theme"

# SEO settings
jekyll-seo-tag:
  author: "Federico Dattila"
