title: "Federico Dattila - The carbon dioxide hunter"
email: "federico.dattila@polito.it"
description: "Welcome to my personal website, featuring myself, my research, my communication activities."
baseurl: "" # The subpath of your site, e.g., /blog
url: "https://fededat.github.io" # Your GitHub Pages URL

# Navigation
nav:
  - Home: /
  - About Federico: /about-federico/
  - Book an activity: /communication/
  - Upcoming Events: /events/
  - Research: /research/
  - Courses: /courses/
  - Contacts: /contacts/

header_pages:
  - about-federico.md
  - communication.md
  - events.md
  - research.md
  - courses.md
  - contacts.md

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Exclude files from processing
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Theme configuration (optional, if using a specific theme)
theme: minima

# Footer information
footer:
  hosting: "Hosted on GitHub Pages"
  theme_credit: "Using Minima theme"

# SEO settings
jekyll-seo-tag:
  lang: "en"
  author: "Federico Dattila"
